package advisor.http.service;

public class RequestServiceTestUtils {
  static final String NEWS_RELEASES_JSON =
      "{\n"
          + "  \"albums\" : {\n"
          + "    \"href\" : \"https://api.spotify.com/v1/browse/new-releases?country=SE&offset=0&limit=20\",\n"
          + "    \"items\" : [ {\n"
          + "      \"album_type\" : \"single\",\n"
          + "      \"artists\" : [ {\n"
          + "        \"external_urls\" : {\n"
          + "          \"spotify\" : \"https://open.spotify.com/artist/2RdwBSPQiwcmiDo9kixcl8\"\n"
          + "        },\n"
          + "        \"href\" : \"https://api.spotify.com/v1/artists/2RdwBSPQiwcmiDo9kixcl8\",\n"
          + "        \"id\" : \"2RdwBSPQiwcmiDo9kixcl8\",\n"
          + "        \"name\" : \"Pharrell Williams\",\n"
          + "        \"type\" : \"artist\",\n"
          + "        \"uri\" : \"spotify:artist:2RdwBSPQiwcmiDo9kixcl8\"\n"
          + "      } ],\n"
          + "      \"available_markets\" : [ \"AD\", \"AR\", \"AT\", \"AU\", \"BE\", \"BG\", \"BO\", \"BR\", \"CA\", \"CH\", \"CL\", \"CO\", \"CR\", \"CY\", \"CZ\", \"DE\", \"DK\", \"DO\", \"EC\", \"EE\", \"ES\", \"FI\", \"FR\", \"GB\", \"GR\", \"GT\", \"HK\", \"HN\", \"HU\", \"ID\", \"IE\", \"IS\", \"IT\", \"JP\", \"LI\", \"LT\", \"LU\", \"LV\", \"MC\", \"MT\", \"MX\", \"MY\", \"NI\", \"NL\", \"NO\", \"NZ\", \"PA\", \"PE\", \"PH\", \"PL\", \"PT\", \"PY\", \"SE\", \"SG\", \"SK\", \"SV\", \"TR\", \"TW\", \"US\", \"UY\" ],\n"
          + "      \"external_urls\" : {\n"
          + "        \"spotify\" : \"https://open.spotify.com/album/5ZX4m5aVSmWQ5iHAPQpT71\"\n"
          + "      },\n"
          + "      \"href\" : \"https://api.spotify.com/v1/albums/5ZX4m5aVSmWQ5iHAPQpT71\",\n"
          + "      \"id\" : \"5ZX4m5aVSmWQ5iHAPQpT71\",\n"
          + "      \"images\" : [ {\n"
          + "        \"height\" : 640,\n"
          + "        \"url\" : \"https://i.scdn.co/image/e6b635ebe3ef4ba22492f5698a7b5d417f78b88a\",\n"
          + "        \"width\" : 640\n"
          + "      }, {\n"
          + "        \"height\" : 300,\n"
          + "        \"url\" : \"https://i.scdn.co/image/92ae5b0fe64870c09004dd2e745a4fb1bf7de39d\",\n"
          + "        \"width\" : 300\n"
          + "      }, {\n"
          + "        \"height\" : 64,\n"
          + "        \"url\" : \"https://i.scdn.co/image/8a7ab6fc2c9f678308ba0f694ecd5718dc6bc930\",\n"
          + "        \"width\" : 64\n"
          + "      } ],\n"
          + "      \"name\" : \"Runnin'\",\n"
          + "      \"type\" : \"album\",\n"
          + "      \"uri\" : \"spotify:album:5ZX4m5aVSmWQ5iHAPQpT71\"\n"
          + "    }, {\n"
          + "      \"album_type\" : \"single\",\n"
          + "      \"artists\" : [ {\n"
          + "        \"external_urls\" : {\n"
          + "          \"spotify\" : \"https://open.spotify.com/artist/3TVXtAsR1Inumwj472S9r4\"\n"
          + "        },\n"
          + "        \"href\" : \"https://api.spotify.com/v1/artists/3TVXtAsR1Inumwj472S9r4\",\n"
          + "        \"id\" : \"3TVXtAsR1Inumwj472S9r4\",\n"
          + "        \"name\" : \"Drake\",\n"
          + "        \"type\" : \"artist\",\n"
          + "        \"uri\" : \"spotify:artist:3TVXtAsR1Inumwj472S9r4\"\n"
          + "      } ],\n"
          + "      \"available_markets\" : [ \"AD\", \"AR\", \"AT\", \"AU\", \"BE\", \"BG\", \"BO\", \"BR\", \"CH\", \"CL\", \"CO\", \"CR\", \"CY\", \"CZ\", \"DE\", \"DK\", \"DO\", \"EC\", \"EE\", \"ES\", \"FI\", \"FR\", \"GB\", \"GR\", \"GT\", \"HK\", \"HN\", \"HU\", \"ID\", \"IE\", \"IS\", \"IT\", \"JP\", \"LI\", \"LT\", \"LU\", \"LV\", \"MC\", \"MT\", \"MY\", \"NI\", \"NL\", \"NO\", \"NZ\", \"PA\", \"PE\", \"PH\", \"PL\", \"PT\", \"PY\", \"SE\", \"SG\", \"SK\", \"SV\", \"TR\", \"TW\", \"UY\" ],\n"
          + "      \"external_urls\" : {\n"
          + "        \"spotify\" : \"https://open.spotify.com/album/0geTzdk2InlqIoB16fW9Nd\"\n"
          + "      },\n"
          + "      \"href\" : \"https://api.spotify.com/v1/albums/0geTzdk2InlqIoB16fW9Nd\",\n"
          + "      \"id\" : \"0geTzdk2InlqIoB16fW9Nd\",\n"
          + "      \"images\" : [ {\n"
          + "        \"height\" : 640,\n"
          + "        \"url\" : \"https://i.scdn.co/image/d40e9c3d22bde2fbdb2ecc03cccd7a0e77f42e4c\",\n"
          + "        \"width\" : 640\n"
          + "      }, {\n"
          + "        \"height\" : 300,\n"
          + "        \"url\" : \"https://i.scdn.co/image/dff06a3375f6d9b32ecb081eb9a60bbafecb5731\",\n"
          + "        \"width\" : 300\n"
          + "      }, {\n"
          + "        \"height\" : 64,\n"
          + "        \"url\" : \"https://i.scdn.co/image/808a02bd7fc59b0652c9df9f68675edbffe07a79\",\n"
          + "        \"width\" : 64\n"
          + "      } ],\n"
          + "      \"name\" : \"Sneakin’\",\n"
          + "      \"type\" : \"album\",\n"
          + "      \"uri\" : \"spotify:album:0geTzdk2InlqIoB16fW9Nd\"\n"
          + "    } ],\n"
          + "    \"limit\" : 20,\n"
          + "    \"next\" : \"https://api.spotify.com/v1/browse/new-releases?country=SE&offset=20&limit=20\",\n"
          + "    \"offset\" : 0,\n"
          + "    \"previous\" : null,\n"
          + "    \"total\" : 500\n"
          + "  }\n"
          + "}";
  static final String FEATURED_PLAYLIST_JSON =
      "{\n"
          + "  \"message\" : \"Monday morning music, coming right up!\",\n"
          + "  \"playlists\" : {\n"
          + "    \"href\" : \"https://api.spotify.com/v1/browse/featured-playlists?country=SE&timestamp=2015-05-18T06:44:32&offset=0&limit=2\",\n"
          + "    \"items\" : [ {\n"
          + "      \"collaborative\" : false,\n"
          + "      \"description\" : \"Relaxed deep house to slowly help you get back on your feet and ready yourself for a productive week.\",\n"
          + "      \"external_urls\" : {\n"
          + "        \"spotify\" : \"http://open.spotify.com/user/spotify/playlist/6ftJBzU2LLQcaKefMi7ee7\"\n"
          + "      },\n"
          + "      \"href\" : \"https://api.spotify.com/v1/users/spotify/playlists/6ftJBzU2LLQcaKefMi7ee7\",\n"
          + "      \"id\" : \"6ftJBzU2LLQcaKefMi7ee7\",\n"
          + "      \"images\" : [ {\n"
          + "        \"height\" : 300,\n"
          + "        \"url\" : \"https://i.scdn.co/image/7bd33c65ebd1e45975bbcbbf513bafe272f033c7\",\n"
          + "        \"width\" : 300\n"
          + "      } ],\n"
          + "      \"name\" : \"Monday Morning Mood\",\n"
          + "      \"owner\" : {\n"
          + "        \"external_urls\" : {\n"
          + "          \"spotify\" : \"http://open.spotify.com/user/spotify\"\n"
          + "        },\n"
          + "        \"href\" : \"https://api.spotify.com/v1/users/spotify\",\n"
          + "        \"id\" : \"spotify\",\n"
          + "        \"type\" : \"user\",\n"
          + "        \"uri\" : \"spotify:user:spotify\"\n"
          + "      },\n"
          + "      \"public\" : null,\n"
          + "      \"snapshot_id\" : \"WwGvSIVUkUvGvqjgj/bQHlRycYmJ2TkoIxYfoalWlmIZT6TvsgvGMgtQ2dGbkrAW\",\n"
          + "      \"tracks\" : {\n"
          + "        \"href\" : \"https://api.spotify.com/v1/users/spotify/playlists/6ftJBzU2LLQcaKefMi7ee7/tracks\",\n"
          + "        \"total\" : 245\n"
          + "      },\n"
          + "      \"type\" : \"playlist\",\n"
          + "      \"uri\" : \"spotify:user:spotify:playlist:6ftJBzU2LLQcaKefMi7ee7\"\n"
          + "    }, {\n"
          + "      \"collaborative\" : false,\n"
          + "      \"description\" : \"Du kommer studsa ur sängen med den här spellistan.\",\n"
          + "      \"external_urls\" : {\n"
          + "        \"spotify\" : \"http://open.spotify.com/user/spotify__sverige/playlist/4uOEx4OUrkoGNZoIlWMUbO\"\n"
          + "      },\n"
          + "      \"href\" : \"https://api.spotify.com/v1/users/spotify__sverige/playlists/4uOEx4OUrkoGNZoIlWMUbO\",\n"
          + "      \"id\" : \"4uOEx4OUrkoGNZoIlWMUbO\",\n"
          + "      \"images\" : [ {\n"
          + "        \"height\" : 300,\n"
          + "        \"url\" : \"https://i.scdn.co/image/24aa1d1b491dd529b9c03392f350740ed73438d8\",\n"
          + "        \"width\" : 300\n"
          + "      } ],\n"
          + "      \"name\" : \"Upp och hoppa!\",\n"
          + "      \"owner\" : {\n"
          + "        \"external_urls\" : {\n"
          + "          \"spotify\" : \"http://open.spotify.com/user/spotify__sverige\"\n"
          + "        },\n"
          + "        \"href\" : \"https://api.spotify.com/v1/users/spotify__sverige\",\n"
          + "        \"id\" : \"spotify__sverige\",\n"
          + "        \"type\" : \"user\",\n"
          + "        \"uri\" : \"spotify:user:spotify__sverige\"\n"
          + "      },\n"
          + "      \"public\" : null,\n"
          + "      \"snapshot_id\" : \"0j9Rcbt2KtCXEXKtKy/tnSL5r4byjDBOIVY1dn4S6GV73EEUgNuK2hU+QyDuNnXz\",\n"
          + "      \"tracks\" : {\n"
          + "        \"href\" : \"https://api.spotify.com/v1/users/spotify__sverige/playlists/4uOEx4OUrkoGNZoIlWMUbO/tracks\",\n"
          + "        \"total\" : 38\n"
          + "      },\n"
          + "      \"type\" : \"playlist\",\n"
          + "      \"uri\" : \"spotify:user:spotify__sverige:playlist:4uOEx4OUrkoGNZoIlWMUbO\"\n"
          + "    } ],\n"
          + "    \"limit\" : 2,\n"
          + "    \"next\" : \"https://api.spotify.com/v1/browse/featured-playlists?country=SE&timestamp=2015-05-18T06:44:32&offset=2&limit=2\",\n"
          + "    \"offset\" : 0,\n"
          + "    \"previous\" : null,\n"
          + "    \"total\" : 12\n"
          + "  }\n"
          + "}";
  static final String CATEGORIES_PLAYLIST_JSON =
      "{\n"
          + "  \"playlists\" : {\n"
          + "    \"href\" : \"https://api.spotify.com/v1/browse/categories/party/playlists?country=BR&offset=0&limit=2\",\n"
          + "    \"items\" : [ {\n"
          + "      \"collaborative\" : false,\n"
          + "      \"description\" : \"Chegou o grande dia, aperte o play e partiu fim de semana!\",\n"
          + "      \"external_urls\" : {\n"
          + "        \"spotify\" : \"https://open.spotify.com/playlist/37i9dQZF1DX8mBRYewE6or\"\n"
          + "      },\n"
          + "      \"href\" : \"https://api.spotify.com/v1/playlists/37i9dQZF1DX8mBRYewE6or\",\n"
          + "      \"id\" : \"37i9dQZF1DX8mBRYewE6or\",\n"
          + "      \"images\" : [ {\n"
          + "        \"height\" : 300,\n"
          + "        \"url\" : \"https://i.scdn.co/image/ab67706f00000002206a95fa5badbe1d33b65e14\",\n"
          + "        \"width\" : 300\n"
          + "      } ],\n"
          + "      \"name\" : \"Sexta\",\n"
          + "      \"owner\" : {\n"
          + "        \"display_name\" : \"Spotify\",\n"
          + "        \"external_urls\" : {\n"
          + "          \"spotify\" : \"https://open.spotify.com/user/spotify\"\n"
          + "        },\n"
          + "        \"href\" : \"https://api.spotify.com/v1/users/spotify\",\n"
          + "        \"id\" : \"spotify\",\n"
          + "        \"type\" : \"user\",\n"
          + "        \"uri\" : \"spotify:user:spotify\"\n"
          + "      },\n"
          + "      \"primary_color\" : null,\n"
          + "      \"public\" : null,\n"
          + "      \"snapshot_id\" : \"MTU3NDM1NjI0MiwwMDAwMDAwMGQ0MWQ4Y2Q5OGYwMGIyMDRlOTgwMDk5OGVjZjg0Mjdl\",\n"
          + "      \"tracks\" : {\n"
          + "        \"href\" : \"https://api.spotify.com/v1/playlists/37i9dQZF1DX8mBRYewE6or/tracks\",\n"
          + "        \"total\" : 62\n"
          + "      },\n"
          + "      \"type\" : \"playlist\",\n"
          + "      \"uri\" : \"spotify:playlist:37i9dQZF1DX8mBRYewE6or\"\n"
          + "    }, {\n"
          + "      \"collaborative\" : false,\n"
          + "      \"description\" : \"O batidão dos funks mais bombados pra agitar a pista do seu baile! [Conteúdo explícito]\",\n"
          + "      \"external_urls\" : {\n"
          + "        \"spotify\" : \"https://open.spotify.com/playlist/37i9dQZF1DWWmaszSfZpom\"\n"
          + "      },\n"
          + "      \"href\" : \"https://api.spotify.com/v1/playlists/37i9dQZF1DWWmaszSfZpom\",\n"
          + "      \"id\" : \"37i9dQZF1DWWmaszSfZpom\",\n"
          + "      \"images\" : [ {\n"
          + "        \"height\" : 300,\n"
          + "        \"url\" : \"https://pl.scdn.co/images/pl/default/68fae5be6747e445c6bb34655c2bc2a77b9d1439\",\n"
          + "        \"width\" : 300\n"
          + "      } ],\n"
          + "      \"name\" : \"Segue o Baile\",\n"
          + "      \"owner\" : {\n"
          + "        \"display_name\" : \"Spotify\",\n"
          + "        \"external_urls\" : {\n"
          + "          \"spotify\" : \"https://open.spotify.com/user/spotify\"\n"
          + "        },\n"
          + "        \"href\" : \"https://api.spotify.com/v1/users/spotify\",\n"
          + "        \"id\" : \"spotify\",\n"
          + "        \"type\" : \"user\",\n"
          + "        \"uri\" : \"spotify:user:spotify\"\n"
          + "      },\n"
          + "      \"primary_color\" : null,\n"
          + "      \"public\" : null,\n"
          + "      \"snapshot_id\" : \"MTU3MzEyOTM2OCwwMDAwMDA5MDAwMDAwMTZlNDVkMTM0MmMwMDAwMDE2ZGNjMTY1NTFh\",\n"
          + "      \"tracks\" : {\n"
          + "        \"href\" : \"https://api.spotify.com/v1/playlists/37i9dQZF1DWWmaszSfZpom/tracks\",\n"
          + "        \"total\" : 67\n"
          + "      },\n"
          + "      \"type\" : \"playlist\",\n"
          + "      \"uri\" : \"spotify:playlist:37i9dQZF1DWWmaszSfZpom\"\n"
          + "    } ],\n"
          + "    \"limit\" : 2,\n"
          + "    \"next\" : \"https://api.spotify.com/v1/browse/categories/party/playlists?country=BR&offset=2&limit=2\",\n"
          + "    \"offset\" : 0,\n"
          + "    \"previous\" : null,\n"
          + "    \"total\" : 37\n"
          + "  }\n"
          + "}";
}
